### ISSUE TITLE
When I run owfuzzer,the target network has been disconnected?

### ISSUE THREAD

**Issue by Mrxia111** [alipay/Owfuzz#11]
The mode of running owfuzzy is AP. Just after running for a while, the following situation occurred.
![_U25ZZRQNR{`B)9QDN6 BWD](https://user-images.githubusercontent.com/92384670/160394137-214f6093-7dc1-465a-9d38-edbd8528315f.png)

**Comment by Mrxia111** [comment]
Could you give me some advice?

**Comment by Flynask** [comment]
I had the same issue, it's linked to your target not receiving ping or not responding to it. Make sure your target is not blocking ICMP packets as it would fail the fuzzer call to **check_alive_by_ping()** to check your target availability.

**Comment by Mrxia111** [comment]
Because the system will use ping function in AP mode, if the development board and the target to be tested are not in the same LAN, an error will be reported
