### ISSUE TITLE
When I input the command line, the interface is always like this and there is no response

### ISSUE THREAD

**Issue by Mrxia111** [alipay/Owfuzz#12]
The same command line can run normally in the previous experiment, but now suddenly there is no response.
![1](https://user-images.githubusercontent.com/92384670/165700383-f3395f93-3314-41e8-b20e-96571e268af9.png)
Could you give me some advice.

**Comment by Mrxia111** [comment]
> The same command line can run normally in the previous experiment, but now suddenly there is no response. ![1](https://user-images.githubusercontent.com/92384670/165700383-f3395f93-3314-41e8-b20e-96571e268af9.png) Could you give me some advice.

![WY7(`JGPJO3YQCL9`MJF_C9](https://user-images.githubusercontent.com/92384670/165702982-2f4e2a47-2dfd-44c7-b1b4-4345543dd24d.png)
here is the result of executing the file of openwifi_ owfuzz.sh. 
 Is it related to the RF board

**Comment by Mrxia111** [comment]
After the breakpoint is set in the code, it is found that the data packet received each time is not the data packet between the development board and the test target. See the code below.
Code path：owfuzz\src\fuzz_control.c         in    void* start_fuzzing(void *param)
![`B7KRKO}}75FB6ZP7H Z%3B](https://user-images.githubusercontent.com/92384670/165719915-2ea15d74-dd0f-49b6-af42-838fa73b8881.png)
Is there only two reasons: the development board is not connected with the test target, and there is a problem with the RF module of the development board.
I feel that the development board and the test target are connected by using the MAC address in the command line. Does this mean that the development board and the test target must be connected？
If there is a problem with the RF module of the development board, how to test it？
could you give me some advice. thank you!

**Comment by E7mer** [comment]
Hi, it filters packets by mac address, if there is no packet from bssid or target mac,  it will looks like 'no response'

**Comment by Mrxia111** [comment]
Because the input parameter - C channel is inconsistent with the target to be measured, there will be no response if there is no data packet between them.
