### ISSUE TITLE
Error modifying channel when running the program

### ISSUE THREAD

**Issue by Mrxia111** [alipay/Owfuzz#14]
When I was running, I encountered the following error.
![信道出错](https://user-images.githubusercontent.com/92384670/166210372-ce82f2f2-9e68-4d75-b004-2246f0f9b05e.png)
then,I found that the channel setting failed by adding the printf function to the source code.
![信道问题](https://user-images.githubusercontent.com/92384670/166210621-4fe9bca7-51d9-4008-b435-f43f0624b92e.png)
![image](https://user-images.githubusercontent.com/92384670/166210704-f22ba7af-8f5c-4b34-a36c-a34a9bd1585a.png)
Specific code path：owfuzz/src/fuzz_control.c             int oi_init() function
Why is this happening？could you give me some advice. thank you!

**Comment by Mrxia111** [comment]
On the issue of channel modification, I found that the statement in this function has not been executed successfully
code path: owfuzz\linux_wifi\control\capture_linux_wifi\linux_wireless_control.c  iwconfig_set_channel() function
![3](https://user-images.githubusercontent.com/92384670/166238224-aeaba8fe-90ff-4a3c-a779-041867a11929.png)
why? Which direction should I analyze.
could you give me some advice. thank you.

**Comment by E7mer** [comment]
Try 'iwconfig sdr0 channel 161', it may not be supported.
