### ISSUE TITLE
When initializing the file, the result is like this. Is it normal？

### ISSUE THREAD

**Issue by Mrxia111** [alipay/Owfuzz#9]
The picture is as follows
![1](https://user-images.githubusercontent.com/92384670/155970738-4986218b-6e51-45fd-bda9-a7613d1a1e60.png)
![2](https://user-images.githubusercontent.com/92384670/155970746-76e8de96-8125-4e60-b574-d87bcc7f84fe.png)
![(L2LD91J)P(4NEQQZ3D(N%M](https://user-images.githubusercontent.com/92384670/155970754-9eabb7de-0de8-4cc3-a6cd-2a8537051d1c.png)

**Comment by E7mer** [comment]
Yes. This is normal.

**Comment by Mrxia111** [comment]
![}9))_J K(FF129PI353U$KR](https://user-images.githubusercontent.com/92384670/156880706-e28eee12-98e2-495a-b464-50c0cf1bbfb2.png)
However, in this picture, the physical address of sdr0 has become like this. If the test mode is sta mode, is the - s parameter 66-55-44-33-22-d8-30-30-00-00-00-00-00-00-00-00 filled in

**Comment by Mrxia111** [comment]
![J{~SQ}58Y5ETG3HBUIK6ZP5](https://user-images.githubusercontent.com/92384670/156905983-7121ad3e-40a0-41fa-ac72-b7f11bfa4225.png)
When I input the MAC address, why is the printed MAC address different from the one I input
